// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 26 Jan 2019 17:58:05 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package lv2host provides Go bindings for simple LV2 host
*/
package lv2host
