// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 25 Jan 2019 22:19:09 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package lv2host

/*
#cgo pkg-config: lilv-0
#cgo LDFLAGS: -L./lv2host/ -llv2host-c -lstdc++
#include "lv2host/lv2host-c.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// CLV2Host type as declared in lv2host/lv2host-c.h:10
type CLV2Host unsafe.Pointer
